<?php
session_start();

use PHPMailer\PHPMailer\PHPMailer;
include_once "PHPMailer/PHPMailer.php";
include_once "PHPMailer/Exception.php";
include_once "PHPMailer/SMTP.php";

$mail= new PHPMailer();
$mail->isSMTP();
$mail->Host = "smtp.mailtrap.io";
$mail->SMTPAuth = true;
$mail->Username= "5cd5fea3f3fc71";
$mail->Password = "a92c49b8b02398";
$mail->SMTPSecure = "TLS";
$mail->Port = "587";

$mail->setFrom('info@mailtrap.io', 'Mailtrap');
$mail->addAddress('recipient1@mailtrap.io', 'Tim');
$mail->Subject = "Test Email via Mailtrap SMTP using PHPMailer";
$mail->isHTML(true);
$mailContent = "Send HTML Email using SMTP in PHP. This is a test email I am sending using SMTP mail server with PHPMailer.";
$mail->Body = $mailContent;

if($mail->send()){
   echo $msg = "Your email has been send.";
}
else{
    echo $msg = "Error Sending Mail.";
}
        
/*session_start();
require_once 'C:/xampp/phpMyAdmin/vendor/autoload.php';
$from = 'Your Hotel <confirmation@hotel.com>';
$to = 'Me <me@gmail.com>';
$subject = 'Thanks for choosing Our Hotel!';

$headers = ['From' => $from,'To' => $to, 'Subject' => $subject];

// include text and HTML versions
$text = 'Hi there, we are happy to confirm your booking. Please check the document in the attachment.';
$html = 'Hi there, we are happy to <br>confirm your booking.</br> Please check the document in the attachment.';

//add  attachment
$file = '/confirmations/yourbooking.pdf';

$mime = new Mail_mime();
$mime->setTXTBody($text);
$mime->setHTMLBody($html);
$mime->addAttachment($file, 'text/plain');

$body = $mime->get();
$headers = $mime->headers($headers);

$host = 'smtp.mailtrap.io';
$username = '5cd5fea3f3fc71'; // generated by Mailtrap
$password = 'a92c49b8b02398'; // generated by Mailtrap
$port = '2525';

$smtp = Mail::factory('smtp', [
  'host' => $host,
  'auth' => true,
  'username' => $username,
  'password' => $password,
  'port' => $port
]);

$mail = $smtp->send($to, $headers, $body);

if (PEAR::isError($mail)) {
    echo('<p>' . $mail->getMessage() . '</p>');
} else {
    echo('<p>Message successfully sent!</p>');
}
*/


        /* require 'C:\xampp\phpMyAdmin\vendor\autoload.php'; //include the Composer generated autoload.php file
        use PHPMailer\PHPMailer\PHPMailer;
        //$mail = new PHPMailer(); //create a new PHPMailer object
        //SMTP configuration
        $phpmailer = new PHPMailer();
        $phpmailer->isSMTP();
        $phpmailer->Host = 'smtp.mailtrap.io';
        $phpmailer->SMTPAuth = true;
        $phpmailer->Username = '5cd5fea3f3fc71';
        $phpmailer->Password = 'a92c49b8b02398';
        $phpmailer->Port = 2525;

        //Specify PHPMailer headers
        $phpmailer->setFrom('info@mailtrap.io', 'Mailtrap');
        $phpmailer->addReplyTo('info@mailtrap.io', 'Mailtrap');
        $phpmailer->addAddress('recipient1@mailtrap.io', 'Tim');
        $phpmailer->addCC('cc1@example.com', 'Elena');
        $phpmailer->addBCC('bcc1@example.com', 'Alex');

        $phpmailer->Subject = 'Test Email via Mailtrap SMTP using PHPMailer'; //Setting subject
        $phpmailer->isHTML(true); //setting the email format to HTML
        $mailContent = "<h1>Send HTML Email using SMTP in PHP</h1>
        <p>This is a test email I’m sending using SMTP mail server with PHPMailer.</p>";
        $phpmailer->Body = $mailContent;
        $phpmailer->msgHTML(file_get_contents('contents.html'), __DIR__);
        if($phpmailer->send()){
            echo 'Message has been sent';
        }else{
            echo 'Message could not be sent.';
            echo 'Mailer Error: ' . $phpmailer->ErrorInfo;
        }

       $to = "rajni9338@gmail.com";
        //$from = "rajni.gulati@blazeclan.com";
        $subject = "Shared Credentials";
        //$headers = ['From' => $from,'To' => $to, 'Subject' => $subject];
        $headers = "From: rajni.gulati@blazeclan.com";

        $message = "Please use these credentials to login";

        
        mail($to, $subject, $message, $headers);
        echo "Message has been sent";*/

    ?>